all_metrics = [
    {
        "ts": "1703484955810",
        "stable_name": "taosx_sys",
        "tags": [{"name": "taosx_id", "value": "taosx_id_1"}],
        "metrics": [
            {"name": "sys_cpu_cores", "value": "12f64"},
            {"name": "sys_total_memory", "value": "8000000000"},
            {"name": "sys_used_memory", "value": "4000000000f64"},
            {"name": "sys_available_memory", "value": "2000000000f64"},
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_net_read_bytes", "value": "6000000000f64"},
            {"name": "process_net_written_bytes", "value": "6000000000f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
            {"name": "running_tasks", "value": "31f64"},
            {"name": "completed_tasks", "value": "32f64"},
            {"name": "failed_tasks", "value": "33f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_agent",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "agent_id", "value": "agent_id_1"},
            {"name": "agent_name", "value": "agent_name_1"},
        ],
        "metrics": [
            {"name": "sys_cpu_cores", "value": "12f64"},
            {"name": "sys_total_memory", "value": "8000000000"},
            {"name": "sys_used_memory", "value": "4000000000f64"},
            {"name": "sys_available_memory", "value": "2000000000f64"},
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_start_time", "value": "350f64"},
            {"name": "process_id", "value": "12343f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_agent",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "agent_id", "value": "agent_id_2"},
            {"name": "agent_name", "value": "agent_name_2"},
        ],
        "metrics": [
            {"name": "sys_cpu_cores", "value": "12f64"},
            {"name": "sys_total_memory", "value": "8000000000"},
            {"name": "sys_used_memory", "value": "4000000000f64"},
            {"name": "sys_available_memory", "value": "2000000000f64"},
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_start_time", "value": "350f64"},
            {"name": "process_id", "value": "12343f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "influxdb"},
            {"name": "task_id", "value": "task_id_6"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "opentsdb"},
            {"name": "task_id", "value": "task_id_7"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "opcua"},
            {"name": "task_id", "value": "task_id_2"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "opcda"},
            {"name": "task_id", "value": "task_id_opcda_1"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "pi"},
            {"name": "task_id", "value": "task_id_8"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "pibackfill"},
            {"name": "task_id", "value": "task_id_9"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "mqtt"},
            {"name": "task_id", "value": "task_id_4"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_connector",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "ds_name", "value": "mqtt"},
            {"name": "task_id", "value": "task_id_5"},
        ],
        "metrics": [
            {"name": "process_uptime", "value": "100f64"},
            {"name": "process_cpu_percent", "value": "30f64"},
            {"name": "process_memory_percent", "value": "30f64"},
            {"name": "process_disk_read_bytes", "value": "6000000000f64"},
            {"name": "process_disk_written_bytes", "value": "6000000000f64"},
            {"name": "process_id", "value": "12343f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_tdengine2",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_13"},
            {"name": "task_name", "value": "task_name_13"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "read_concurrency", "value": "123f64"},
            {"name": "total_stables", "value": "12f64"},
            {"name": "total_updated_tags", "value": "11f64"},
            {"name": "total_created_tables", "value": "12340f64"},
            {"name": "total_tables", "value": "12345f64"},
            {"name": "total_finished_tables", "value": "1234f64"},
            {"name": "total_success_blocks", "value": "123450f64"},
            {"name": "finished_tables", "value": "12345f64"},
            {"name": "success_blocks", "value": "12345f64"},
            {"name": "created_tables", "value": "12345f64"},
            {"name": "updated_tags", "value": "15f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_tdengine3",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_1"},
            {"name": "task_name", "value": "task_name_1"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_messages", "value": "1234567f64"},
            {"name": "total_messages_of_meta", "value": "1234f64"},
            {"name": "total_messages_of_data", "value": "12345f64"},
            {"name": "total_write_raw_fails", "value": "12f64"},
            {"name": "total_success_blocks", "value": "123455f64"},
            {"name": "topics", "value": "12f64"},
            {"name": "consumers", "value": "123f64"},
            {"name": "messages", "value": "12345678f64"},
            {"name": "messages_of_meta", "value": "12345f64"},
            {"name": "messages_of_data", "value": "123456f64"},
            {"name": "write_raw_fails", "value": "15f64"},
            {"name": "success_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_opcua",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_2"},
            {"name": "task_name", "value": "task_name_2"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_opcua",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_3"},
            {"name": "task_name", "value": "task_name_3"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_opcda",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_opcda_1"},
            {"name": "task_name", "value": "task_name_opcda_1"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_mqtt",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_4"},
            {"name": "task_name", "value": "task_name_4"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_mqtt",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_5"},
            {"name": "task_name", "value": "task_name_5"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_influxdb",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_6"},
            {"name": "task_name", "value": "task_name_6"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_opentsdb",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_7"},
            {"name": "task_name", "value": "task_name_7"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_pi",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_8"},
            {"name": "task_name", "value": "task_name_8"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_pibackfill",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_9"},
            {"name": "task_name", "value": "task_name_9"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_csv",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_10"},
            {"name": "task_name", "value": "task_name_10"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_avevahistorian",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_11"},
            {"name": "task_name", "value": "task_name_11"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
    {
        "ts": "1703484955810",
        "stable_name": "taosx_task_kafka",
        "tags": [
            {"name": "taosx_id", "value": "taosx_id_1"},
            {"name": "task_id", "value": "task_id_12"},
            {"name": "task_name", "value": "task_name_12"},
        ],
        "metrics": [
            {"name": "total_execute_time", "value": "123456f64"},
            {"name": "total_written_rows", "value": "1200f64"},
            {"name": "total_written_points", "value": "60000f64"},
            {"name": "start_time", "value": "12345678f64"},
            {"name": "written_rows", "value": "1234f64"},
            {"name": "written_points", "value": "123400f64"},
            {"name": "execute_time", "value": "12345678f64"},
            {"name": "total_received_batches", "value": "1234567f64"},
            {"name": "total_processed_batches", "value": "1234f64"},
            {"name": "total_processed_rows", "value": "12345f64"},
            {"name": "total_inserted_sqls", "value": "12f64"},
            {"name": "total_failed_sqls", "value": "123455f64"},
            {"name": "total_created_stables", "value": "12f64"},
            {"name": "total_created_tables", "value": "123f64"},
            {"name": "total_failed_rows", "value": "12345678f64"},
            {"name": "total_failed_point", "value": "12345f64"},
            {"name": "total_written_blocks", "value": "123456f64"},
            {"name": "total_failed_blocks", "value": "15f64"},
            {"name": "received_batches", "value": "15000f64"},
            {"name": "processed_batches", "value": "15000f64"},
            {"name": "processed_rows", "value": "15000f64"},
            {"name": "received_records", "value": "15000f64"},
            {"name": "insert_sqls", "value": "15000f64"},
            {"name": "failed_sqls", "value": "15000f64"},
            {"name": "created_stables", "value": "15000f64"},
            {"name": "created_tables", "value": "15000f64"},
            {"name": "failed_rows", "value": "15000f64"},
            {"name": "failed_points", "value": "15000f64"},
            {"name": "written_blocks", "value": "15000f64"},
            {"name": "failed_blocks", "value": "15000f64"},
        ],
    },
]
