version: '3.6'
services:
  telegraf:
    image: telegraf:1.20-alpine
    hostname: telegraf
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file: tdengine.env
    ports:
    - '127.0.0.1:18125:8125/udp'

  grafana:
    image: grafana/grafana:7.5.10
    env_file: tdengine.env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../../dist:/var/lib/grafana/plugins/tdengine
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
