{
 "title": "TDinsight for taosX",
 "description": "Monitor taosX",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Log from",
    "query": "select name from information_schema.ins_databases where `vgroups` is not null ORDER BY CASE WHEN name = 'log' THEN 1 ELSE 2 END, name;"
   },
   {
    "name": "taosX_id",
    "label": "taosX",
    "query": "select distinct(taosx_id) from $database.taosx_sys where _ts >= $from and _ts <= $to"
   },
   {
    "name": "agent_id",
    "label": "Agent",
    "query": "select concat(agent_id, '!', agent_id, '-' ,agent_name) from $database.taosx_agent where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to order by agent_id desc"
   },
   {
    "name": "datasource",
    "label": "DataSource",
    "query": "SELECT 'TDengine2' AS datasource  UNION  SELECT 'TDengine3' UNION  SELECT 'Influxdb' UNION  SELECT 'OpenTSDB' UNION  SELECT 'OPCUA' UNION  SELECT 'OPCDA'  UNION  SELECT 'PI' UNION  SELECT 'PIBackFill' UNION  SELECT 'CSV'UNION  SELECT 'MQTT' UNION SELECT 'AvevaHistorian' UNION  SELECT 'Kafka' order by datasource"
   },
   {
    "name": "task",
    "label": "Task",
    "query": "select distinct concat(task_id, '!', task_id, '-' ,task_name) from $database.taosx_task_$datasource where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "taosX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>taosX Dashboard (ID: ${taosX_id})</center></h1>"
   },
   "targets": [
    { "formatType": "Time series" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(sys_cpu_cores) as cpus from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(sys_total_memory)/(1024*1024*1024) from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "cpu_taosx",
     "formatType": "Table",
     "sql": "select last(process_cpu_percent)  from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "mem_taosx",
     "formatType": "Time series",
     "sql": "select last(process_memory_percent) as memory from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(process_uptime)as seconds from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "mem_taosx",
     "formatType": "Time series",
     "sql": "select count(*) - 1 as restart_times from (select distinct(process_id) from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to);"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(process_cpu_percent) as cpu_usage from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(process_memory_percent) as memory_usage from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(running_tasks) as running_tasks from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval($interval) fill(VALUE, null);"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, sum(failed_tasks) as failed_tasks from log.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval($interval) fill(VALUE, 0);"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, sum(completed_tasks) as completed_tasks from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval($interval) fill(VALUE, 0);"
    }
   ]
  },
  {
   "title": "Agent [ $agent_id ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "agent_id",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(sys_cpu_cores) as cpus from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": " select last(sys_total_memory)/(1024*1024*1024) from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(process_uptime)as seconds from  $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "cpu_taosx",
       "formatType": "Table",
       "sql": "select last(process_cpu_percent)  from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosx",
       "formatType": "Time series",
       "sql": "select last(process_memory_percent) as memory from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(process_cpu_percent) as cpu_usage  from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id'  and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(process_memory_percent) as memory_usage from $database.taosx_agent where taosx_id = '$taosX_id' and agent_id = '$agent_id' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "TDengine3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_tdengine3 where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_tdengine3 where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'TDengine3' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_tdengine3 where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'TDengine3' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Write Raw Fails",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  last(total_write_raw_fails) - first(total_write_raw_fails) as write_raw_fails from $database.taosx_task_tdengine3 where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'TDengine3' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "TDengine2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_tdengine2 where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_tdengine2 where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'TDengine2' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_tdengine2 where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'TDengine2' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "PIBackFill",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_pibackfill where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pibackfill' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pibackfill' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pibackfill' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pibackfill' and ('$task' = '' OR task_id = '$task' or 'PIBackFill' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "PI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_pi where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_pi where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_pi where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_pi where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_pi where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_pi where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pi' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pi' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pi' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'pi' and ('$task' = '' OR task_id = '$task' or 'PI' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenTSDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_opentsdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opentsdb' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opentsdb' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opentsdb' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opentsdb' and ('$task' = '' OR task_id = '$task' or 'OpenTSDB' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "OPC-UA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_opcua where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_opcua where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_opcua where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_opcua where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_opcua where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_opcua where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcua' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcua' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcua' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcua' and ('$task' = '' OR task_id = '$task' or 'OPCUA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "OPC-DA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_opcda where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_opcda where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_opcda where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_opcda where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_opcda where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_opcda where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcda' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcda' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcda' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'opcda' and ('$task' = '' OR task_id = '$task' or 'OPCDA' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "MQTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_mqtt where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'mqtt' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'mqtt' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'mqtt' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'mqtt' and ('$task' = '' OR task_id = '$task' or 'MQTT' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_kafka where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_kafka where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Kafka' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_kafka where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Kafka' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_kafka where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Kafka' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_kafka where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Kafka' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_kafka where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Kafka' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_influxdb where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector CPU Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_cpu_percent) as process_cpu_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'influxdb' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_memory_percent) as process_memory_percent from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'influxdb' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_read_bytes) as process_disk_read_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'influxdb' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Connector Disk Written Bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, avg(process_disk_written_bytes) as process_disk_written_bytes from $database.taosx_connector where taosx_id = '$taosX_id' and ds_name = 'influxdb' and ('$task' = '' OR task_id = '$task' or 'Influxdb' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "CSV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_csv where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_csv where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'CSV' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_csv where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'CSV' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_csv where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'CSV' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_csv where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'CSV' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_csv where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'CSV' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    }
   ]
  },
  {
   "title": "AvevaHistorian",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select task_id, task_name, last(execute_time) as execute_time, last(written_rows) as written_rows, last(total_execute_time) as total_execute_time, last(total_written_rows) as total_written_rows  from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to  partition by task_id, task_name order by task_id desc"
      }
     ]
    },
    {
     "title": "Inserted rows Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_rows) - min(total_written_rows)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as rows_per_second from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'AvevaHistorian' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Inserted Points Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (max(total_written_points) - min(total_written_points)) * 1000 / (max(total_execute_time) - min(total_execute_time)) as points_per_second from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'AvevaHistorian' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Processed/Received Batches",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}_processed_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_processed_batches) - first(total_processed_batches)) as processed_batches from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'AvevaHistorian' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      },
      {
       "colNameFormatStr": "{{task_id}}_received_batches",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id,  (last(total_received_batches) - first(total_received_batches)) as received_batches from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'AvevaHistorian' not in (${datasource:sqlstring})) and  _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    },
    {
     "title": "Failed Sqls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "colNameFormatStr": "{{task_id}}",
       "colNameToGroup": "task_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, task_id, (last(total_failed_sqls) - first(total_failed_sqls)) as failed_sqls from $database.taosx_task_avevaHistorian where taosx_id = '$taosX_id' and ('$task' = '' OR task_id = '$task' or 'AvevaHistorian' not in (${datasource:sqlstring})) and _ts >= $from and _ts <= $to  partition by task_id  interval(1m) fill(null) order by task_id"
      }
     ]
    }
   ]
  }
 ]
}