{
 "title": "TDinsight for taosX",
 "description": "Monitor taosX",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Log from",
    "query": "select name from information_schema.ins_databases where `vgroups` is not null"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "taosX_id",
    "label": "taosX",
    "query": "select distinct(taosx_id) from $database.taosx_sys where _ts >= $from and _ts <= $to"
   },
   {
    "name": "agent_id",
    "label": "Agent",
    "query": "select distinct(agent_id) from $database.taosx_agent where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
   },
   {
    "name": "datasource",
    "label": "DataSource",
    "query": "SELECT 'TDengine2' AS datasource  UNION  SELECT 'TDengine3' UNION  SELECT 'Influxdb'UNION  SELECT 'Opentsdb'UNION  SELECT 'OPC'UNION  SELECT 'PI'UNION  SELECT 'CSV'UNION  SELECT 'MQTT'UNION\n SELECT 'Hisotorian'UNION  SELECT 'Kafka' order by datasource"
   },
   {
    "name": "task",
    "label": "Task",
    "query": "select distinct(task_id) from $database.taosx_task_$datasource where  _ts >= $from and _ts <= $to"
   }
  ]
 },
 "panels": [
  {
   "title": "taosX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>taosX Dashboard (ID: ${taosX_id})</center></h1>"
   },
   "targets": [
    { "formatType": "Time series" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(sys_cpu_cores) as cpus from $database.taosx_sys"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(sys_total_memory)/(1024*1024*1024) from $database.taosx_sys"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(uptime)as seconds from $database.taosx_sys  where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "CPU Usage of taosX",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "cpu_taosd",
     "formatType": "Table",
     "sql": "select last(process_cpu_percent)  from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Memory Usage of taosX",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "mem_taosd",
     "formatType": "Time series",
     "sql": "select last(process_memory_percent) as memory from $database.taosx_sys where taosx_id = '$taosX_id' and _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "CPU Usage of taosX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(process_cpu_percent) as cpu_usage from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Memory Usage of taosX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(process_memory_percent) as memory_usage from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(running_tasks) as running_tasks from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Failed Tasks in Last 24h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(failed_tasks_in_24h) as failed_tasks_in_24h from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Complete Tasks in Last 24h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(complete_tasks_in_24h) as complete_tasks_in_24h from $database.taosx_sys where taosx_id = '$taosX_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Agent [ $agent_id ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "agent_id",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(sys_cpu_cores) as cpus from $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": " select last(sys_total_memory)/(1024*1024*1024) from $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(uptime)as seconds from  $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Usage of Agent",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "cpu_taosd",
       "formatType": "Table",
       "sql": "select last(process_cpu_percent)  from $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Memory Usage of Agent",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 17, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosd",
       "formatType": "Time series",
       "sql": "select last(process_memory_percent) as memory from $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Usage of Agent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(process_cpu_percent) as cpu_usage  from $database.taosx_agent where agent_id = '$agent_id'  and _ts >= $from and _ts <= $to interval(30s) fill(null)"
      }
     ]
    },
    {
     "title": "Memory Usage of Agent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 13, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(process_memory_percent) as memory_usage from $database.taosx_agent where agent_id = '$agent_id' and _ts >= $from and _ts <= $to interval(30s) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "OPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select task_id, last(execute_time) as uptime, last(written_rows) as written_rows  from $database.taosx_task_opc  where _ts >= $from and _ts <= $to  partition by task_id "
    }
   ]
  },
  {
   "title": "Insert rows Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(rows_per_second) as rows_per_second from $database.taosx_task_opc where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Insert Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(points_per_second) as points_per_second from $database.taosx_task_opc where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Processed/Received Batches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}_processed_batches",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(processed_batches) as processed_batches from $database.taosx_task_opc where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    },
    {
     "colNameFormatStr": "{{task_id}}_received_batches",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(processed_batches) as processed_batches from $database.taosx_task_opc where ('$task' = '' OR task_id = '$task') and  _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Failed Sqls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(failed_sqls) as failed_sqls from $database.taosx_task_opc where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Task Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select task_id, last(execute_time) as uptime, last(written_rows) as written_rows  from $database.taosx_task_mqtt  where _ts >= $from and _ts <= $to  partition by task_id "
    }
   ]
  },
  {
   "title": "Insert rows Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(rows_per_second) as rows_per_second from $database.taosx_task_mqtt where ('$task' = '' OR task_id = '$task') and  _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Insert Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(points_per_second) as points_per_second from $database.taosx_task_mqtt where ('$task' = '' OR task_id = '$task') and  _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Processed/Received Batches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}_processed_batches",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(processed_batches) as processed_batches from $database.taosx_task_mqtt where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    },
    {
     "colNameFormatStr": "{{task_id}}_received_batches",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(processed_batches) as processed_batches from $database.taosx_task_mqtt where ('$task' = '' OR task_id = '$task') and  _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Failed Sqls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(failed_sqls) as failed_sqls from $database.taosx_task_mqtt where ('$task' = '' OR task_id = '$task') and _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  { "title": "TDengine 3.x", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Task Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select task_id, last(execute_time) as uptime, last(written_rows) as written_rows  from $database.taosx_task_tdengine3  where _ts >= $from and _ts <= $to  partition by task_id "
    }
   ]
  },
  {
   "title": "Insert rows Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(rows_per_second) as rows_per_second from $database.taosx_task_tdengine3 where _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Insert Points Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(points_per_second) as points_per_second from $database.taosx_task_tdengine3 where _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  },
  {
   "title": "Write Raw Fails",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "colNameFormatStr": "{{task_id}}",
     "colNameToGroup": "task_id",
     "formatType": "Time series",
     "sql": "select _wstart as ts, task_id,  avg(write_raw_fails) as write_raw_fails from $database.taosx_task_tdengine3 where _ts >= $from and _ts <= $to  partition by task_id  interval($interval) fill(null) order by task_id"
    }
   ]
  }
 ]
}