{
 "title": "TDinsight for 3.x",
 "description": "Monitor TDengine",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Log from",
    "query": "select name from information_schema.ins_databases where `vgroups` is not null ORDER BY CASE WHEN name = 'log' THEN 1 ELSE 2 END, name;"
   },
   {
    "name": "fqdn",
    "query": "select distinct dnode_ep  from $database.taosd_dnodes_info where _ts >= $from and _ts <= $to"
   },
   {
    "name": "version",
    "query": "select last(cluster_version) from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
   },
   {
    "name": "firstEp",
    "query": "select last(first_ep) from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
   },
   {
    "name": "username",
    "label": "User",
    "query": "select distinct username  from $database.taos_sql_req where _ts >= $from and _ts <= $to"
   },
   {
    "name": "sql_result",
    "label": "SqlResult",
    "query": "select distinct result  from $database.taos_sql_req where _ts >= $from and _ts <= $to"
   },
   {
    "name": "duration",
    "label": "SlowSqlDuration",
    "query": "select distinct `duration`  from $database.taos_slow_sql where _ts >= $from and _ts <= $to"
   },
   {
    "name": "adapter_endpoint",
    "label": "adapter_endpoint",
    "query": "select  distinct endpoint  from $database.adapter_requests where ts >= $from and ts <= $to order by endpoint"
   },
   {
    "name": "last_dnodes_ts",
    "label": "last_dnodes_ts",
    "query": "select last(_ts) from $database.taosd_dnodes_status"
   },
   {
    "name": "last_mnodes_ts",
    "label": "last_mnodes_ts",
    "query": "select last(_ts) from $database.taosd_mnodes_info"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    { "formatType": "Time series" }
   ]
  },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(first_ep) as first_ep from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(cluster_version) as version from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": " select case when grants_expire_time > (50 * 365 * 24 * 3600) then cast ('unlimited' as binary(100)) else grants_expire_time end as grants_expire_time from (select last(grants_expire_time) as grants_expire_time from $database.taosd_cluster_info where _ts >= $from and _ts <= $to)"
    }
   ]
  },
  {
   "title": "Used Measuring Points",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select max(grants_timeseries_used) as used ,max(grants_timeseries_total) as total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval)"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(dbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Stables & Tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(stbs_total + tbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select connections_total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select dnodes_total as total, dnodes_alive as dnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select mnodes_total as total, mnodes_alive as mnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vgroups_total as total, vgroups_alive as vgroups_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vnodes_total as total, vnodes_alive as vnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(dnodes_alive)/avg(dnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(mnodes_alive)/avg(mnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vgroups_alive)/avg(vgroups_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vnodes_alive)/avg(vnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Measuring Points Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(grants_timeseries_used)/avg(grants_timeseries_total) as percent from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    },
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(grants_timeseries_used) as used , avg(grants_timeseries_total) as total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "DNodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNodes Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select dnode_ep,  last(`status`) as status from $database.taosd_dnodes_status where _ts = '$last_dnodes_ts' group by dnode_ep order by dnode_ep"
      }
     ]
    },
    {
     "title": "DNodes Number",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(dnodes_total) as total, max(dnodes_alive) as dnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "MNodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "MNodes Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select mnode_ep, last(role) as role from $database.taosd_mnodes_info where _ts = '$last_mnodes_ts' group by mnode_ep order by mnode_ep"
      }
     ]
    },
    {
     "title": "MNodes Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(mnodes_total) as total, max(mnodes_alive) as mnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts,  avg(`count`) as `select_count`  from $database.taos_sql_req where sql_type = 'select' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Delete Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(`count`) as `delete_count`  from $database.taos_sql_req where sql_type = 'delete' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Insert Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts,  avg(`count`) as `insert_count`  from $database.taos_sql_req where sql_type = 'insert' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Inserted Rows",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(`count`) as `inserted_rows`  from $database.taosd_sql_req where sql_type = 'inserted_rows' and   ('$fqdn' = '' or  dnode_ep in (${fqdn:sqlstring})) and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Slow SQL",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(`count`) as `count`  from $database.taos_slow_sql where ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring})) and  ('$duration' = '' OR `duration` in (${duration:sqlstring})) and _ts > $from and _ts <= $to interval($interval) fill(VALUE, 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "STables",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "select last(stbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, last(tbs_total) as tables_num from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Tables Number Foreach VGroups",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "colNameFormatStr": "vgroup_{{vgroup_id}}",
       "colNameToGroup": "vgroup_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, vgroup_id, max(tables_num) as tables_num from $database.taosd_vgroups_info where _ts >= $from and _ts <= $to partition by vgroup_id interval($interval) fill(null) order by vgroup_id"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "select last(tbs_total) as tbs_total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(uptime) as uptime from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Has MNode?",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(has_mnode) as has_mnode from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 6, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(cpu_cores) as cpu_cores from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "VNodes Number",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 8, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(vnodes_num) as vnodes_num from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "VNodes Masters",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 10, "y": 68 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(masters) as masters from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Current CPU Usage of taosd",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "cpu_taosd",
       "formatType": "Table",
       "sql": "select last(cpu_engine) from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Current Memory Usage of taosd",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosd",
       "formatType": "Time series",
       "sql": "select last(mem_engine) as taosd, last(mem_total) as total from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Max Disk Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_taosd",
       "formatType": "Time series",
       "sql": "select max(percent) as percent from (select data_dir_level, data_dir_name,last(used/total) as percent from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(cpu_engine) as taosd, avg(cpu_system) as `system` from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, last(mem_engine) as taosd, last(mem_free) as `free`, last(mem_total) as total from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "colNameFormatStr": "L{{data_dir_level}}-{{data_dir_name}}-used",
       "colNameToGroup": "data_dir_level, data_dir_name",
       "formatType": "Time series",
       "sql": "select _wstart as ts, data_dir_level, data_dir_name, last(used) as used from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name interval($interval) fill(null) order by data_dir_level, data_dir_name"
      },
      {
       "colNameFormatStr": "L{{data_dir_level}}-{{data_dir_name}}-total",
       "colNameToGroup": "data_dir_level, data_dir_name",
       "formatType": "Time series",
       "sql": "select _wstart as ts, data_dir_level, data_dir_name, last(total) as total from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name interval($interval) fill(null) order by data_dir_level, data_dir_name"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(io_read_disk) as taosd_io_read, avg(io_write_disk) as taosd_io_write from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, 0 - avg(system_net_in) as system_net_in, avg(system_net_out) as system_net_out from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "TaosAdapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "RESTful Requests",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select sum(`total`) as `Total`, sum(`success`) as `Successful`, sum(`fail`) as `Failed`, sum(`query`) as `Queries`, sum(`write`) as `Writes`, sum(`other`) as `Other` from $database.adapter_requests where req_type=0 and ts >= $from and ts <= $to"
      }
     ]
    },
    {
     "title": "request by rest",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "colNameFormatStr": "{{endpoint}}_queries",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query`)/($interval/1s) as `query` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_success`)/($interval/1s) as `query_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_fail`)/($interval/1s) as `query_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_in_process",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_in_process`)/($interval/1s) as `query_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_writes",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write`)/($interval/1s) as `write` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_success`)/($interval/1s) as `write_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_fail`)/($interval/1s) as `write_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_in_process",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_in_process`)/($interval/1s) as `write_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_others",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other`)/($interval/1s) as `other` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_other_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_success`)/($interval/1s) as `other_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_other_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_fail`)/($interval/1s) as `other_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "WebSocket Requests",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select sum(`total`) as `Total`, sum(`success`) as `Successful`, sum(`fail`) as `Failed`, sum(`query`) as `Queries`, sum(`write`) as `Writes`, sum(`other`) as `Other` from $database.adapter_requests where req_type=1 and ts >= $from and ts <= $to"
      }
     ]
    },
    {
     "title": "request by ws",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "colNameFormatStr": "{{endpoint}}_queries",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query`)/($interval/1s) as `query` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_success`)/($interval/1s) as `query_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_fail`)/($interval/1s) as `query_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_query_in_process",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_in_process`)/($interval/1s) as `query_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_writes",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write`)/($interval/1s) as `write` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_success`)/($interval/1s) as `write_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_fail`)/($interval/1s) as `write_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_write_in_process",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_in_process`)/($interval/1s) as `write_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_others",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other`)/($interval/1s) as `other` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_other_successful",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_success`)/($interval/1s) as `other_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "colNameFormatStr": "{{endpoint}}_other_failed",
       "colNameToGroup": "endpoint",
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_fail`)/($interval/1s) as `other_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Used Only",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNodes Offline",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "cluster_id",
       "formatType": "Time series",
       "sql": "select first(_ts),  cluster_id, last(dnodes_total)  - last(dnodes_alive) as dnode_offline  from log.taosd_cluster_info where _ts >= (now -30s) and _ts < now partition by cluster_id"
      }
     ]
    },
    {
     "title": "VNodes Offline",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "cluster_id",
       "formatType": "Time series",
       "sql": "select first(_ts),  cluster_id, last(vnodes_total)  - last(vnodes_alive) as vnode_offline  from log.taosd_cluster_info where _ts >= (now - 30s) and _ts < now partition by cluster_id"
      }
     ]
    },
    {
     "title": "Expire Time Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "cluster_id",
       "formatType": "Time series",
       "sql": "select first(_ts), cluster_id, last(grants_expire_time) / 86400 as expire_time from log.taosd_cluster_info where  _ts >= (now - 24h)  and _ts < now  partition by cluster_id",
       "timeShiftUnit": "days"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts,  dnode_ep, avg(cpu_system) as `system` from log.taosd_dnodes_info where _ts >= $from and _ts <= $to partition by dnode_ep  interval(5m) fill(null)"
      }
     ]
    },
    {
     "title": "Disk Used Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_id, data_dir_level, data_dir_name",
       "formatType": "Time series",
       "sql": "select first(_ts), dnode_id, data_dir_level, data_dir_name, last(used)  / last(total)  * 100 as used from log.taosd_dnodes_data_dirs where _ts >= (now - 5m) and _ts < now partition by dnode_id, data_dir_level, data_dir_name ",
       "timeShiftPeriod": "0",
       "timeShiftUnit": "minutes"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_id",
       "formatType": "Time series",
       "sql": "select first(_ts), dnode_id, last(mem_engine) / last(mem_total)  * 100 as taosd from log.taosd_dnodes_info where _ts >= (now- 5m) and _ts <now partition by dnode_id",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "Used Measuring Points",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "colNameToGroup": "cluster_id",
       "formatType": "Time series",
       "sql": " select  first(_ts), cluster_id,  CASE  WHEN max(grants_timeseries_total)  > 0 THEN max(grants_timeseries_used)  /max(grants_timeseries_total) * 100   ELSE 0    END AS result from log.taosd_cluster_info where _ts >= (now - 30s) and _ts < now partition by cluster_id",
       "timeShiftPeriod": "1",
       "timeShiftUnit": "days"
      }
     ]
    },
    {
     "title": "Query Count Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select first(_ts),  count(*) as `select_count`  from log.taos_sql_req where sql_type = 'select'  and _ts >= (now- 1m) and _ts <now ",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "Slow Query Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select now() as ts, count(*) as slow_count from performance_schema.perf_queries where exec_usec>300000000",
       "timeShiftPeriod": "0",
       "timeShiftUnit": "minutes"
      }
     ]
    },
    {
     "title": "Dnodes reboot alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_id",
       "formatType": "Time series",
       "sql": "select first(_ts),  dnode_id,  max(uptime) - last(uptime) as dnode_report  from log.taosd_dnodes_info where _ts >= (now - 90s) and _ts < now  partition by dnode_id ",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "Adapter Websocket Failed Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select first(ts), sum(`fail`) as `Failed` from log.adapter_requests where req_type=1 and ts >= (now -30s) and ts < now",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "DNodes Metrics Report Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "cluster_id",
       "formatType": "Time series",
       "sql": "select first(_ts),  cluster_id, count(*) as dnode_report  from log.taosd_cluster_info where _ts >= (now -180s) and _ts < now partition by cluster_id ",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "Adapter RESTful Failed Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select first(ts), sum(`fail`) as `Failed` from log.adapter_requests where req_type=0 and ts >= (now -30s) and ts < now;",
       "timeShiftPeriod": "0",
       "timeShiftUnit": "seconds"
      }
     ]
    },
    {
     "title": "Delete Request Alert",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select  first(_ts),  count(`count`)  as `delete_count`  from log.taos_sql_req  where sql_type = 'delete' and _ts >= (now -30s) and _ts < now",
       "timeShiftUnit": "seconds"
      }
     ]
    }
   ]
  }
 ]
}