{
 "title": "TDinsight",
 "description": "Monitor TDengine with alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "show databases" },
   {
    "name": "fqdn",
    "query": "select first_ep from $database.cluster_info group by cluster_id, first_ep;"
   },
   {
    "name": "version",
    "query": "select last(version) from $database.cluster_info"
   },
   {
    "name": "firstEp",
    "query": "select last(first_ep) from $database.cluster_info"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    {
     "alias": "mnodes",
     "formatType": "Time series",
     "sql": "select mnode_ep,mnode_id,last(status) as status from $database.m_info group by mnode_ep, cluster_id",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(first_ep) from $database.cluster_info group by first_ep;",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(version) from $database.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master Uptime",
   "type": "stat",
   "description": "MNode 被选举后经过的时长",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(master_uptime) from $database.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "description": "企业版授权到期时间",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(expire_time) from $database.grants_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Used Measuring Points",
   "type": "bargauge",
   "description": "企业版授权已用测点数",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select max(timeseries_used) as used ,max(timeseries_total) as total from $database.grants_info where ts >= $from and ts <= $to interval(30s)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "description": "数据库个数",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "formatType": "Time series",
     "sql": "select last(dbs_total) from $database.cluster_info;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "description": "所有数据库的表数量之和",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "formatType": "Time series",
     "sql": "select last(tbs_total) from $database.cluster_info;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select connections_total from $database.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "description": "当前TDengine集群DNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select dnodes_total as total,dnodes_alive as alive from $database.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "description": "当前TDengine集群MNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select mnodes_total as total,mnodes_alive as alive from $database.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "description": "当前TDengine集群 VGroups 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vgroups_total as total, vgroups_alive as alive from $database.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "description": "当前TDengine集群 VNodes 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vnodes_total as total, vnodes_alive as alive from $database.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(dnodes_alive)/avg(dnodes_total) from $database.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(mnodes_alive)/avg(mnodes_total) from $database.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vgroups_alive)/avg(vgroups_total) from $database.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vnodes_alive)/avg(vnodes_total) from $database.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Measuring Points Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(timeseries_used)/avg(timeseries_total) as percent from $database.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(timeseries_used) as used , avg(timeseries_total) as total from $database.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Grants Expire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, last(expire_time) as expire_time from $database.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "错误率（每秒错误数）",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, derivative(errors, 1s, 1) as errors from (select _wstart as ts, sum(errors) as errors from $database.dnodes_info where ts >= $from and ts <= $to interval(1s))",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "DNodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "DNodes Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select dnode_ep, last(status) as status from hlb.d_info partition by dnode_ep, cluster_id;",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "colNameFormatStr": "{{groupValue}}",
     "colNameToGroup": "dnode_ep",
     "formatType": "Time series",
     "sql": "select last(uptime) from $database.dnodes_info where ts >= $from and ts <= $to group by dnode_ep",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(dnodes_total) as total, avg(dnodes_alive) as alive from $database.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "MNodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "MNodes Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select dnode_ep, last(status) as status from $database.d_info partition by dnode_ep, cluster_id;",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Number",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(mnodes_total) as total, avg(mnodes_alive) as alive from $database.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Rate (Inserts per Second)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(req_insert_rate) as insert_rate, avg(req_insert_batch_rate) as batch_rate from $database.dnodes_info where ts >= $from and ts <= $to partition by dnode_ep interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(insert_rate) as cluster_insert_rate, avg(batch_rate) as cluster_batch_rate from (select _wstart as ts, sum(req_insert_rate) as insert_rate, sum(req_insert_batch_rate) as batch_rate from $database.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Requests (Selects)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select _wstart as ts, sum(req_select) as req_select from $database.dnodes_info where ts >= $from and ts <= $to partition by dnode_ep interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select _wstart as ts, sum(req_select) as total from $database.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(req_select_rate) as req_select_rate from $database.dnodes_info where ts >= $from and ts <= $to partition by dnode_ep interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(req_select_rate) as req_select_rate from (select _wstart as ts, sum(req_select_rate) as req_select_rate from $database.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Database: [ $database ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "database",
   "collapsed": true,
   "panels": [
    {
     "title": "STables",
     "type": "stat",
     "description": "超级表的个数",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "select last(stbs_total) from $database.cluster_info",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, last(tables_num) as tables_num from $database.vgroups_info where ts > $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Tables Number Foreach VGroups",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "colNameFormatStr": "vgoup{{groupValue}}",
       "colNameToGroup": "vgroup_id",
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(tables_num) as tables_num from $database.vgroups_info where ts > $from and ts <= $to partition by vgroup_id interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Total Tables",
     "type": "stat",
     "description": "所有普通表的个数（包括超级表的子表）",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "select last(tbs_total) as tbs_total from $database.cluster_info where first_ep = '$fqdn';",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "启动时长",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(uptime) as uptime from $database.dnodes_info where dnode_ep = '$fqdn'",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Has MNode?",
     "type": "stat",
     "description": "是否有MNode",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(has_mnode) as has_mnode from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "CPU 核数",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(cpu_cores) as cpu_cores from $database.dnodes_info where dnode_ep = '$fqdn' interval ($interval)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Number",
     "type": "stat",
     "description": "VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(vnodes_num) as vnodes_num from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Masters",
     "type": "stat",
     "description": "Master VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(masters) as masters from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current CPU Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 CPU 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosd",
       "formatType": "Table",
       "sql": "select last(cpu_engine) from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current Memory Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 内存 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "memory",
       "formatType": "Time series",
       "sql": "select last(mem_engine) as taosd, last(mem_total) as total from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(disk_used) as used, last(disk_total) as total, last(disk_used) / last(disk_total) as percent from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU 资源占用情况。",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent", "label": "使用占比" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(cpu_engine) as taosd, avg(cpu_system) as system from $database.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "description": "内存资源占用情况",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "deckbytes", "label": "使用占比" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(mem_engine) as taosd, avg(mem_system) as system, avg(mem_total) as total from $database.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(used) as level0_used, avg(total) as level0_total from $database.data_dir where level = 0 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(used) as level1_used, avg(total) as level1_total from $database.data_dir where level = 1 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(used) as level2_used, avg(total) as level2_total from $database.data_dir where level = 2 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(used)/avg(total) as level0_percent from $database.data_dir where level = 0 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(used)/avg(total) as level1_percent from $database.data_dir where level = 1 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(used)/avg(total) as level2_percent from $database.data_dir where level = 2 and dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used Increasing Rate per Minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "alias": "level0",
       "formatType": "Time series",
       "sql": "select ts, derivative(value1, 1m, 0) as level0 from (select _wstart as ts, avg(used) * 1024 as value1 from $database.data_dir where dnode_ep = '$fqdn' and ts >= $from and ts <= $to and level = 0 interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level1",
       "formatType": "Time series",
       "sql": "select ts, derivative(value1, 1m, 0) as level1 from (select _wstart as ts, avg(used) * 1024 as value1 from $database.data_dir where dnode_ep = '$fqdn' and ts >= $from and ts <= $to and level = 1 interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level2",
       "formatType": "Time series",
       "sql": "select ts, derivative(value1, 1m, 0) as level2 from (select _wstart as ts, avg(used) * 1024 as value1 from $database.data_dir where dnode_ep = '$fqdn' and ts >= $from and ts <= $to and level =2 interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "binBps", "label": "IO Rate" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(io_read_disk) as io_read_taosd, avg(io_write_disk) as io_write_taosd from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Net",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "binBps", "label": "IO Rate" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(net_in) as net_in, avg(net_out) as net_out from $database.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Login History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login Counts per Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "alias": "logins",
       "formatType": "Time series",
       "sql": "select _wstart as ts, count(*) from $database.logs where ts >= $from and ts <= $to interval (1m)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "TaosAdapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_request",
     "type": "timeseries",
     "description": "http请求统计",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(gauge) as request_total from $database.taosadapter_restful_http_request_total where _ts >= $from and _ts <= $to interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(gauge) as request_fail from $database.taosadapter_restful_http_request_fail where _ts >= $from and _ts <= $to interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(gauge) as request_in_flight from $database.taosadapter_restful_http_request_in_flight where _ts >= $from and _ts <= $to interval($interval)"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(gauge) as mem_percent from $database.taosadapter_system_mem_percent where _ts >= $from and _ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Used",
     "type": "gauge",
     "description": "CPU 使用率",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(gauge) as cpu_percent from $database.taosadapter_system_cpu_percent where _ts >= $from and _ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  }
 ]
}