{
 "title": "DBMart Power Plants Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Fleet Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fleet Total Generation (past minute)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_unit_1_total_watts_1eejc0620 where ts > (now - 1m) interval(1m)"
    },
    {
     "alias": "Site A MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9019 where ts > (now - 10m) interval(1m)"
    },
    {
     "alias": "Site B MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_planttotalcalc where ts > (now - 30m) interval(1m)"
    }
   ]
  },
  {
   "title": "Fleet Total Generation (24 hr)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 1 },
   "targets": [
    {
     "alias": "Site C MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_unit_1_total_watts_1eejc0620 where ts > (now - 24h) interval(1m)",
     "timeshift": { "unit": "hours" }
    },
    {
     "alias": "Site A MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9019 where ts > (now - 24h) interval(1m)",
     "timeshift": { "unit": "hours" }
    },
    {
     "alias": "Site B MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_planttotalcalc where ts > (now - 24h) interval(5m)",
     "timeshift": { "unit": "hours" }
    }
   ]
  },
  {
   "title": "Heat Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitec_bst_hr_heat_rate where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Site A",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitea_par_hr_heat_rate where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A & Site C LMP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "alias": "Site C LMP",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_lmp_qse where ts > (now - 24h) interval(1m)"
    },
    {
     "alias": "Site A LMP",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_lmp_qse where ts > (now - 24h) interval(1m)"
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_ct_ambient_temp_1cwti0400 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Site A",
     "formatType": "Time series",
     "sql": "select ts,val from `powerplantrealtime`.mg_sitea_par_ti9098 where ts > (now - 1h)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Site B",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u1_ambienttemp where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "BP QSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_basepoint_qse where ts > (now - 1h) interval(1m)"
    },
    {
     "alias": "Site A",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_basepoint_qse where ts > (now - 1h) interval(1m)"
    }
   ]
  },
  {
   "title": "HSL QSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C HSL",
     "formatType": "Time series",
     "sql": "SELECT _wstart, avg(val) FROM `powerplantrealtime`.mg_sitec_bas_hsl_qse where ts > (now - 1h) INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Site A HSL",
     "formatType": "Time series",
     "sql": "SELECT _wstart, avg(val) FROM `powerplantrealtime`.mg_sitea_par_hsl_qse where ts > (now - 1h) INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  { "title": "Site C", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BKR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitec_bst_dig_11_1ex_cb_a_gtg1_bkr_status_1eexl1626",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitec_bst_dig_12_1ep_sg_a_bkr_52_2_status_1eexl2664",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitec_bst_dig_00_swyd_bkr_1ey_cb_c_status_0eexl0606",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "MW",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 1, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_11_gtdl_generator_watts_11dwatt where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_12_gtdl_generator_watts_12dwatt where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_1st_trb_0100_stg_watts_1eeji0620a where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "MVR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 MVR",
     "formatType": "Time series",
     "sql": "select ts,val from `powerplantrealtime`.mg_sitec_bst_11_swyd_net_gtg1_mvar_1evji1700b where ts > (now - 1h)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 MVR",
     "formatType": "Time series",
     "sql": "select ts,val from `powerplantrealtime`.mg_sitec_bst_12_swyd_net_gtg2_mvar_1evji2700b where ts > (now - 1h)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG MVR",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_12_gtdl_generator_watts_12dwatt where ts > (now - 24h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "GT Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Temp",
     "formatType": "Time series",
     "sql": "select ts,val from `powerplantrealtime`.mg_sitec_bst_11_gtdl_max_comp_inl_flng_temp_11ctim where ts > (now - 1h)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Temp",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_12_gtdl_max_comp_inl_flng_temp_12ctim where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Freq Bias",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_gt1_freqbias where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_gt2_freqbias where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "E-NOX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 NOX #/hr",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_11_nox_lbshr_1hrai1512 where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 NOX #/hr",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_sitec_bst_12_nox_lbshr_1hrai2512 where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "NOX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Nox",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_11_hrsg_nox_corr_15__o2_1hrai1513 where ts > (now - 24h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Nox",
     "formatType": "Time series",
     "sql": "SELECT _wstart, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_12_hrsg_nox_corr_15__o2_1hrai2513 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Duct Burners MMBTU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Duct Burners",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_db1btu where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Duct Burners",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_db2btu where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "IGV 87",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 IGV 87",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_11_gtdl_position_fb_igv_11csgv where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 IGV 87",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_12_gtdl_position_fb_igv_12csgv where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Temp Contr~0",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_11_gtdl_position_fb_igv_11csgv where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_12_gtdl_position_fb_igv_12csgv where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site C MW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_unit_1_total_watts_1eejc0620 where ts > (now - 1h) interval(1m)"
    }
   ]
  },
  {
   "title": "MMBTU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ENT Daily Total",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_total_btu_today_0fgaqi0202b where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "ENT Yesterday Total",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_btu_yesterday_0fgaqi0202c where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "ENT Instant",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_btu_yesterday_0fgaqi1202c where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "KM Daily Total",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_total_btu_today_0fgaqi1202b where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "KM Yesterday Total",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_btu_yesterday_0fgaqi1202c where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "KM Instant",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_instan_btu_0fgaqi1202a where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site C QSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LMP",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bas_lmp_qse where ts > (now-1m) INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "BasePoint",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_basepoint_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "HSL",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_hsl_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "LSL",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_lsl_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Gas Presure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Inlet Pressure",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_fgdl_pg_e_inlet_press_0fgpi0200 where ts > (now-30m) INTERVAL(1m)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "GT1 Heating Valve",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_fgdl_heating_value_0fgai0200b where ts >  (now-30m) INTERVAL(1m)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "GT2 Inlet Pressure",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_fgdl_pg_e_inlet_press_0fgpi1200 where ts >  (now-30m) INTERVAL(1m)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "GT2 Heating Valve",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_fgdl_heating_value_0fgai1200b where ts >  (now-30m) INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "HP Exh",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "STG HP Upper Met Temp",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_stg_hp_up_innr_mtl_temp_1stti0512 where ts > (now-10m) INTERVAL(2s)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "STG HP Lwr Met Temp",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_stg_hp_low_innr_mtl_temp_1stti0511 where ts > (now - 10m) interval(2s)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "STG HP UpperEx Temp",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_stg_hp_up_innr_mtl_temp_exh_1stti0510 where ts > (now - 10m) interval(2s)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "STG HP Lwr Ext Temp",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_stg_hp_low_innr_mtl_temp_exh_1stti0509 where ts > (now - 10m) interval(2s)",
     "timeshift": { "unit": "seconds" }
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site C",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_ct_ambient_temp_1cwti0400 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site C Heat Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 14 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_hr_heat_rate where ts > now-24h interval(1m)",
     "timeshift": { "unit": "seconds" }
    }
   ]
  },
  {
   "title": "Aux Bus ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aux Bus A",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_1em_sg_a_bus_a_watts_1eeji1635a where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Aux Bus B",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_10_1em_sg_a_bus_b_watts_1eeji2635a where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "DRS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DRS Deployed",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_drs_deploy_qse where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "URS Response",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bas_drs_schedule_qse where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": " RRS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RRS Deployed",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitec_bas_rrs_deployment_qse where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "RRS Response",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitec_bas_rrs_schedule_qse where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "THN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_11_gtdl_hp_turbine_speed_11tnh where ts > (now-10m) INTERVAL(2s)",
     "timeshift": { "unit": "seconds" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitec_bst_12_gtdl_hp_turbine_speed_12tnh where ts > (now - 10m) interval(2s)",
     "timeshift": { "unit": "seconds" }
    }
   ]
  },
  { "title": "Site A", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "BKR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitea_par_gt1brkr",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitea_par_gt2brkr",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG Braker",
     "formatType": "Time series",
     "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_sitea_par_stgbrkr",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A MW",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 1, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "SELECT _WSTART,AVG(val) FROM `powerplantrealtime`.mg_sitea_par_jx1482q_gt1_generator_load where ts > now-1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_sitea_par_jx1782q_gt2_generator_load where ts > now-1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_ji9042 where ts> now-1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A MVR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 1, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 MVR",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9050 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 MVR",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9051 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "STG MVR",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9052 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Freq Bias",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_gt1_freqbias where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_gt2_freqbias where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Emissions NOX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 NOX #/hr",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_cems_nox_mass_ct1 where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 NOX #/hr",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_cems_nox_mass_ct2 where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Emissions NOX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Nox",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_cems_nox_corr_15pct_ct1 where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Nox",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_cems_nox_corr_15pct_ct2 where ts > NOW - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Duct Burners MMBTU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 Duct Burners",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_db1btu where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 Duct Burners",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_db2btu where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "IGV 87",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1 IGV 87",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_11_gtdl_position_fb_igv_11csgv where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2 IGV 87",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitec_bst_12_gtdl_position_fb_igv_12csgv where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Inlet Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GT1",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_tx1433 where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "GT2",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_tx1733 where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A MW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site A MW",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_ji9019 where ts > (now - 1h) interval(1m)"
    }
   ]
  },
  {
   "title": "Total MMBTU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TXOK Daily total MMBTU",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_stabtu_t where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "TXOK Yesterday total MMBTU",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_stabtu_t_yesterday_9am_reset where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "BTU/SCF",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BTU/SCF",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_btuscf where ts > now - 1h interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "Site A Pipeline PSIG",
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_pi5203a where ts > now - 1h INTERVAL(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A QSE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LMP",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_lmp_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "BasePoint",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_basepoint_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "HSL",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_hsl_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "LSL",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_lsl_qse where ts > (now - 1m) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Ambient Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Site A",
     "formatType": "Time series",
     "sql": "select ts,val from `powerplantrealtime`.mg_sitea_par_ti9098 where ts > (now - 1h)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A Heat Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 24 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_sitea_par_hr_heat_rate where ts > now-24h interval(1m)",
     "timeshift": { "unit": "seconds" }
    }
   ]
  },
  {
   "title": "Site A DRS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DRS Deployed",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_drs_deploy_qse where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "URS Response",
     "formatType": "Time series",
     "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_sitea_par_drs_schedule_qse where ts > (now - 1h) interval(1m)",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site A RRS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RRS Deployed",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitea_par_rrs_deployment_qse where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    },
    {
     "alias": "RRS Response",
     "formatType": "Time series",
     "sql": "SELECT ts, val FROM `powerplantrealtime`.mg_sitea_par_rrs_schedule_qse where ts > now - 1h",
     "timeshift": { "unit": "minutes" }
    }
   ]
  },
  {
   "title": "Site B Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "TO Brakers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 1, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "U1 Braker",
       "formatType": "Time series",
       "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_siteb_u1_br"
      },
      {
       "alias": "U2 Braker",
       "formatType": "Time series",
       "sql": "SELECT last(ts, val) FROM `powerplantrealtime`.mg_siteb_u2_br"
      }
     ]
    },
    {
     "title": "Site B Generation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 1, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "U1 Generation",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_siteb_u1_grnetgen where ts > now-1h interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U2 Generation",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_siteb_u2_grnetgen where ts > now-1h INTERVAL(1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    },
    {
     "title": "Coal & Lime Flow Tons/Hr",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "U1 Coal Flow",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_siteb_u1_tcfthrp where ts > now-1h INTERVAL (1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U1 Lime Flow",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_siteb_u1_a016065o calc where ts > now-1h INTERVAL(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U2 Coal Flow",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_siteb_u2_tcfthrp calc where ts > now-1h INTERVAL (1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U2 Lime Flow",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_siteb_u2_a016065o where ts > now-1h INTERVAL(1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    },
    {
     "title": "Emissions",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "U1 Nox",
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u1_eme207 where ts > (now - 1h) interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U1 SO2",
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u1_eme205 where ts > (now - 1h) interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U2 Nox",
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u2_eme207 where ts > (now - 1h) interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "U2 SO2",
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u2_eme205 where ts > (now - 1h) interval(1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    },
    {
     "title": "Site B Heat Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "TO  U1",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_siteb_u1_hrt209 where ts > now-24h interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "TO U2",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_siteb_u1_hrt202 where ts > now-24h INTERVAL (1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    },
    {
     "title": "Site B MW",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_planttotalcalc where ts > (now - 10m) interval(1m)"
      }
     ]
    },
    {
     "title": "Site B Heat Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 14, "y": 11 },
     "targets": [
      {
       "alias": "TO  U1",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, AVG(val) FROM `powerplantrealtime`.mg_siteb_u1_hrt209 where ts > now-24h interval(1m)",
       "timeshift": { "unit": "minutes" }
      },
      {
       "alias": "TO U2",
       "formatType": "Time series",
       "sql": "SELECT _WSTART, avg(val) FROM `powerplantrealtime`.mg_siteb_u1_hrt202 where ts > now-24h INTERVAL (1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    },
    {
     "title": "TO Ambient Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Site B",
       "formatType": "Time series",
       "sql": "select _wstart,avg(val) from `powerplantrealtime`.mg_siteb_u1_ambienttemp where ts > (now - 5m) interval(1m)",
       "timeshift": { "unit": "minutes" }
      }
     ]
    }
   ]
  }
 ]
}