{
 "title": "TDsmeters",
 "description": "TDengine DBMark dmeters database show data",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "1. GLOBAL STATISTIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select count(*) from information_schema.ins_tables where db_name='dmeters' and stable_name='meters';"
    }
   ]
  },
  {
   "title": "Total 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(`count(ts)`) from dmeters.smt1;"
    }
   ]
  },
  { "title": "2. DATA TAKEN BY ONE DEVICE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Last Value ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last_row(*) from dmeters.d0;"
    }
   ]
  },
  {
   "title": "Data taken on one device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last_row(*) from dmeters.d0 interval(40s);"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 13, "x": 0, "y": 22 } },
  {
   "title": "AVG value with interval(30s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 31 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart ,avg(current), avg(voltage), avg(phase) from dmeters.d1 where ts> now-3d  interval(30s);"
    }
   ]
  }
 ]
}