{
 "title": "TDinsight for 3.x",
 "description": "Monitor TDengine",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_TDENGINE", "query": "tdengine-datasource" },
   {
    "name": "database",
    "label": "Log from",
    "query": "select name from information_schema.ins_databases where `vgroups` is not null ORDER BY CASE WHEN name = 'log' THEN 1 ELSE 2 END, name;"
   },
   {
    "name": "fqdn",
    "query": "select distinct dnode_ep  from $database.taosd_dnodes_info where _ts >= $from and _ts <= $to"
   },
   {
    "name": "version",
    "query": "select last(cluster_version) from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
   },
   {
    "name": "firstEp",
    "query": "select last(first_ep) from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
   },
   {
    "name": "username",
    "label": "User",
    "query": "select distinct username  from $database.taos_sql_req where _ts >= $from and _ts <= $to"
   },
   {
    "name": "sql_result",
    "label": "SqlResult",
    "query": "select distinct result  from $database.taos_sql_req where _ts >= $from and _ts <= $to"
   },
   {
    "name": "duration",
    "label": "SlowSqlDuration",
    "query": "select distinct `duration`  from $database.taos_slow_sql where _ts >= $from and _ts <= $to"
   },
   {
    "name": "adapter_endpoint",
    "label": "adapter_endpoint",
    "query": "select  distinct endpoint  from $database.adapter_requests where ts >= $from and ts <= $to order by endpoint"
   },
   {
    "name": "databaseName",
    "query": "select distinct database_name from $database.taosd_write_metrics where _ts >= $from and _ts <= $to"
   },
   {
    "name": "vgroupId",
    "query": "select distinct vgroup_id from $database.taosd_write_metrics where database_name in (${databaseName:sqlstring}) and _ts >= $from and _ts <= $to"
   },
   {
    "name": "last_dnodes_ts",
    "label": "last_dnodes_ts",
    "query": "select last(_ts) from $database.taosd_dnodes_status"
   },
   {
    "name": "last_mnodes_ts",
    "label": "last_mnodes_ts",
    "query": "select last(_ts) from $database.taosd_mnodes_info"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    { "formatType": "Time series" }
   ]
  },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(first_ep) as first_ep from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(cluster_version) as version from $database.taosd_cluster_basic where ts >= $from and ts <= $to"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": " select case when grants_expire_time > (50 * 365 * 24 * 3600) then cast ('unlimited' as binary(100)) else grants_expire_time end as grants_expire_time from (select last(grants_expire_time) as grants_expire_time from $database.taosd_cluster_info where _ts >= $from and _ts <= $to)"
    }
   ]
  },
  {
   "title": "Used Measuring Points",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select max(grants_timeseries_used) as used ,max(grants_timeseries_total) as total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval)"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(dbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Stables & Tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(stbs_total + tbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select connections_total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select dnodes_total as total, dnodes_alive as dnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select mnodes_total as total, mnodes_alive as mnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vgroups_total as total, vgroups_alive as vgroups_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vnodes_total as total, vnodes_alive as vnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
    }
   ]
  },
  {
   "title": "Classified Connection Counts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "formatType": "Table",
     "sql": "select `user`, app, client_ip, count(*) as connection_count from (select *, substring_index(end_point, ':', 1) as client_ip, substring_index(end_point, ':', -1) as client_port from performance_schema.perf_connections) partition by `user`,`app`,`client_ip`"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(dnodes_alive)/avg(dnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(mnodes_alive)/avg(mnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vgroups_alive)/avg(vgroups_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(vnodes_alive)/avg(vnodes_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Measuring Points Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(grants_timeseries_used) as used , avg(grants_timeseries_total) as total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    },
    {
     "formatType": "Time series",
     "sql": "select _wstart as ts, avg(grants_timeseries_used)/avg(grants_timeseries_total) as percent from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
    }
   ]
  },
  {
   "title": "DNodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNodes Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select dnode_ep,  last(`status`) as status from $database.taosd_dnodes_status where _ts = '$last_dnodes_ts' group by dnode_ep order by dnode_ep"
      }
     ]
    },
    {
     "title": "DNodes Number",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(dnodes_total) as total, max(dnodes_alive) as dnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "MNodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "MNodes Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select mnode_ep, last(`role`) as `role` from $database.taosd_mnodes_info where _ts = '$last_mnodes_ts' group by mnode_ep order by mnode_ep"
      }
     ]
    },
    {
     "title": "MNodes Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(mnodes_total) as total, max(mnodes_alive) as mnodes_alive from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts,  sum(`count`)/($interval/1s) as `select_count`  from $database.taos_sql_req where sql_type = 'select' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Delete Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, sum(`count`)/($interval/1s) as `delete_count`  from $database.taos_sql_req where sql_type = 'delete' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Insert Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts,  sum(`count`)/($interval/1s) as `insert_count`  from $database.taos_sql_req where sql_type = 'insert' and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Inserted Rows",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, sum(`count`)/($interval/1s) as `inserted_rows`  from $database.taosd_sql_req where sql_type = 'inserted_rows' and   ('$fqdn' = '' or  dnode_ep in (${fqdn:sqlstring})) and ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring}))  and _ts > $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Slow SQL",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, sum(`count`)/($interval/1s) as `count`  from $database.taos_slow_sql where ('$username' = '' OR username in (${username:sqlstring})) and  ('$sql_result' = '' OR result in (${sql_result:sqlstring})) and  ('$duration' = '' OR `duration` in (${duration:sqlstring})) and _ts > $from and _ts <= $to interval($interval) fill(VALUE, 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "STables",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 75 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(stbs_total) from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, last(tbs_total) as tables_num from $database.taosd_cluster_info where _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Tables Number Foreach VGroups",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, vgroup_id, max(tables_num) as tables_num from $database.taosd_vgroups_info where _ts >= $from and _ts <= $to partition by vgroup_id interval($interval) fill(null) order by vgroup_id"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(tbs_total) as tbs_total from $database.taosd_cluster_info where _ts >= $from and _ts <= $to"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(uptime) as uptime from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Has MNode?",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(has_mnode) as has_mnode from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 6, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(cpu_cores) as cpu_cores from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "VNodes Number",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 8, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(vnodes_num) as vnodes_num from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "VNodes Masters",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 10, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(masters) as masters from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Current CPU Usage of taosd",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select last(cpu_engine) from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Current Memory Usage of taosd",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(mem_engine) as taosd, last(mem_total) as total from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to"
      }
     ]
    },
    {
     "title": "Max Disk Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select max(percent) as percent from (select data_dir_level, data_dir_name,last(used/total) as percent from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(cpu_engine) as taosd, max(cpu_system) as `system` from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, last(mem_engine) as taosd, last(mem_free) as `free`, last(mem_total) as total from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, data_dir_level, data_dir_name, last(used) as used from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name interval($interval) fill(null) order by data_dir_level, data_dir_name"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, data_dir_level, data_dir_name, last(total) as total from $database.taosd_dnodes_data_dirs where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to partition by data_dir_level, data_dir_name interval($interval) fill(null) order by data_dir_level, data_dir_name"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, avg(io_read_disk) as taosd_io_read, avg(io_write_disk) as taosd_io_write from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, 0 - avg(system_net_in) as system_net_in, avg(system_net_out) as system_net_out from $database.taosd_dnodes_info where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Dnode Memory Usage Metrics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, max(rpc_queue_memory_allowed) as rpc_queue_memory_allowed, max(rpc_queue_memory_used) as rpc_queue_memory_used, max(apply_memory_allowed) as apply_memory_allowed, max(apply_memory_used) as apply_memory_used from $database.taosd_dnodes_metrics where dnode_ep = '$fqdn' and _ts >= $from and _ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Rows and Wal Write Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(total_rows) as total_rows from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(wal_write_time) as wal_write_time from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      }
     ]
    },
    {
     "title": "Commit Count and Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(commit_count) as commit_count from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(commit_time) as commit_time from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      }
     ]
    },
    {
     "title": "Blocked Commit Count and Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(blocked_commit_count) as blocked_commit_count from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(blocked_commit_time) as blocked_commit_time from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      }
     ]
    },
    {
     "title": "Merge Count and Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(merge_count) as merge_count from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(merge_time) as merge_time from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      }
     ]
    },
    {
     "title": "Last Cache Commit Count and Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "c/s" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(last_cache_commit_count) as last_cache_commit_count from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, database_name, vgroup_id, avg(last_cache_commit_time) as last_cache_commit_time from $database.taosd_write_metrics where ('$databaseName' = '' or (database_name in (${databaseName:sqlstring}) and ('$vgroupId' = '' or vgroup_id in (${vgroupId:sqlstring})))) and _ts >= $from and _ts <= $to  partition by database_name, vgroup_id interval($interval) fill(null) order by database_name, vgroup_id"
      }
     ]
    }
   ]
  },
  {
   "title": "TaosAdapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "RESTful Requests",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select sum(`total`) as `Total`, sum(`success`) as `Successful`, sum(`fail`) as `Failed`, sum(`query`) as `Queries`, sum(`write`) as `Writes`, sum(`other`) as `Other` from $database.adapter_requests where req_type=0 and ts >= $from and ts <= $to"
      }
     ]
    },
    {
     "title": "request by rest",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query`)/($interval/1s) as `query` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_success`)/($interval/1s) as `query_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_fail`)/($interval/1s) as `query_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_in_process`)/($interval/1s) as `query_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write`)/($interval/1s) as `write` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_success`)/($interval/1s) as `write_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_fail`)/($interval/1s) as `write_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_in_process`)/($interval/1s) as `write_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other`)/($interval/1s) as `other` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_success`)/($interval/1s) as `other_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_fail`)/($interval/1s) as `other_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 0  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "WebSocket Requests",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select sum(`total`) as `Total`, sum(`success`) as `Successful`, sum(`fail`) as `Failed`, sum(`query`) as `Queries`, sum(`write`) as `Writes`, sum(`other`) as `Other` from $database.adapter_requests where req_type=1 and ts >= $from and ts <= $to"
      }
     ]
    },
    {
     "title": "request by ws",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query`)/($interval/1s) as `query` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_success`)/($interval/1s) as `query_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_fail`)/($interval/1s) as `query_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`query_in_process`)/($interval/1s) as `query_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write`)/($interval/1s) as `write` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_success`)/($interval/1s) as `write_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_fail`)/($interval/1s) as `write_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`write_in_process`)/($interval/1s) as `write_in_process` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other`)/($interval/1s) as `other` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_success`)/($interval/1s) as `other_success` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, endpoint, sum(`other_fail`)/($interval/1s) as `other_fail` from $database.adapter_requests where ts >= $from and ts <= $to and req_type = 1  and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Connection Pool",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', `user`, '_', 'total') as label, max(conn_pool_total) as total from $database.adapter_conn_pool where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint, `user` interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', `user`, '_', 'in_use') as label, max(conn_pool_in_use) as in_use from $database.adapter_conn_pool where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint, `user` interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "WebSocket Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', 'ws_query_conn') as label, max(ws_query_conn) from $database.adapter_status where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', 'ws_stmt_conn') as label, max(ws_stmt_conn) from $database.adapter_status where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', 'ws_sml_conn') as label, max(ws_sml_conn) from $database.adapter_status where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', 'ws_ws_conn') as label, max(ws_ws_conn) from $database.adapter_status where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      },
      {
       "formatType": "Time series",
       "sql": "select _wstart as ts, concat(endpoint, '_', 'ws_tmq_conn') as label, max(ws_tmq_conn) from $database.adapter_status where _ts >= $from and _ts <= $to and ('$adapter_endpoint' = '' or  endpoint in (${adapter_endpoint:sqlstring})) partition by endpoint interval($interval) fill(null)"
      }
     ]
    }
   ]
  }
 ]
}