{
 "title": "TDinsight for 2.x",
 "description": "Monitor TDengine with alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "fqdn", "query": "select fqdn from log.dn" },
   { "name": "database", "label": "Database", "query": "show databases" },
   {
    "name": "version",
    "query": "select last(version) from log.cluster_info"
   },
   {
    "name": "firstEp",
    "query": "select last(first_ep) from log.cluster_info"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    {
     "alias": "mnodes",
     "formatType": "Time series",
     "sql": "show mnodes",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(first_ep) from log.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(version) from log.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master Uptime",
   "type": "stat",
   "description": "MNode 被选举后经过的时长",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(master_uptime) from log.cluster_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "description": "企业版授权到期时间",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(expire_time) from log.grants_info",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Used Measuring Points",
   "type": "bargauge",
   "description": "企业版授权已用测点数",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select max(timeseries_used) as used ,max(timeseries_total) as total from log.grants_info where ts >= $from and ts <= $to interval(30s)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "description": "数据库个数",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "formatType": "Time series",
     "sql": "show databases;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "description": "所有数据库的表数量之和",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "formatType": "Time series",
     "sql": "show databases;",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select connections_total from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "description": "当前TDengine集群DNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select dnodes_total as total,dnodes_alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "description": "当前TDengine集群MNode数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select mnodes_total as total,mnodes_alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "description": "当前TDengine集群 VGroups 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vgroups_total as total, vgroups_alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "description": "当前TDengine集群 VNodes 数量，Alive 为存活，Total 为所有",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select vnodes_total as total, vnodes_alive from log.cluster_info where ts >= $from and ts <= $to",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(dnodes_alive)/avg(dnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(mnodes_alive)/avg(mnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(vgroups_alive)/avg(vgroups_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(vnodes_alive)/avg(vnodes_total) from log.cluster_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Measuring Points Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(timeseries_used)/avg(timeseries_total) as percent from log.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "formatType": "Time series",
     "sql": "select avg(timeseries_used) as used , avg(timeseries_total) as total from log.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Grants Expire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select last(expire_time) as expire_time from log.grants_info where ts >= $from and ts <= $to interval(30s) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "错误率（每秒错误数）",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select derivative(errors, 1s, 1) as errors from (select sum(errors) as errors from log.dnodes_info where ts >= $from and ts <= $to interval(1s))",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Variables",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "alias": "dnodes",
     "formatType": "Time series",
     "sql": "show variables",
     "target": "select metric",
     "timeshift": {
      "period": null
     },
     "type": "timeserie"
    }
   ]
  },
  { "title": "DNodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "DNodes Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "formatType": "Table", "sql": "show dnodes", "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "DNodes Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "colNameFormatStr": "{{groupValue}}",
     "colNameToGroup": "dnode_ep",
     "formatType": "Time series",
     "sql": "select last(uptime) from log.dnodes_info where ts >= $from and ts <= $to group by dnode_ep",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(dnodes_total) as total, avg(dnodes_alive) as dnodes_alive from log.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Offline Reasons",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "formatType": "Table", "sql": "show dnodes", "target": "select metric", "type": "timeserie" }
   ]
  },
  { "title": "MNodes Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "MNodes Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "formatType": "Table", "sql": "show mnodes;", "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "MNodes Number",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(mnodes_total) as total, avg(mnodes_alive) as mnodes_alive from log.cluster_info where ts >= $from and ts <= $to interval($interval) fill(null)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Rate (Inserts per Second)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select avg(req_insert_rate) as insert_rate, avg(req_insert_batch_rate) as batch_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(insert_rate) as cluster_insert_rate, avg(batch_rate) as cluster_batch_rate from (select sum(req_insert_rate) as insert_rate, sum(req_insert_batch_rate) as batch_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Requests (Selects)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select sum(req_select) as req_select from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select sum(req_select) as total from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select avg(req_select_rate) as req_select_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select avg(req_select_rate) as req_select_rate from (select sum(req_select_rate) as req_select_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Requests (HTTP)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select sum(req_http) as req_http from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select sum(req_http) as req_http from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null)"
      },
      {
       "colNameToGroup": "dnode_ep",
       "formatType": "Time series",
       "sql": "select avg(req_http_rate) as req_http_rate from log.dnodes_info where ts >= $from and ts <= $to interval($interval) fill(null) group by dnode_ep"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(req_http_rate) as req_http_rate from (select sum(req_http_rate) as req_http_rate from log.dnodes_info where ts >= $from and ts <= $to interval(1s)) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Database: [ $database ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "database",
   "collapsed": true,
   "panels": [
    {
     "title": "STables",
     "type": "stat",
     "description": "超级表的个数",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "show $database.stables;",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "formatType": "Time series",
       "sql": "select last(tables_num) as tables_num from (select last(ts) as ts, sum(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' group by ts) where ts >= $from and ts <= $to interval($interval) fill(null)"
      }
     ]
    },
    {
     "title": "Tables Number Foreach VGroups",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "colName": "vgroup_id",
       "colNameFormatStr": "vgoup{{groupValue}}",
       "colNameToGroup": "vgroup_id",
       "formatType": "Time series",
       "sql": "select max(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' interval($interval) fill(null) group by vgroup_id"
      }
     ]
    },
    {
     "title": "Total Tables",
     "type": "stat",
     "description": "所有普通表的个数（包括超级表的子表）",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "select last(tables_num) from (select last(ts) as ts, sum(tables_num) as tables_num from log.vgroups_info where ts > $from and ts <= $to and database_name = '$database' group by ts)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Sub Tables",
     "type": "stat",
     "description": "超级表的所有子表个数",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 79 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "formatType": "Time series",
       "sql": "show $database.stables;",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "启动时长",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(uptime) as uptime from log.dnodes_info where dnode_ep = '$fqdn'",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Has MNode?",
     "type": "stat",
     "description": "是否有MNode",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(has_mnode) as has_mnode from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      { "alias": "if_has", "expression": "Number(A)", "formatType": "Time series" }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "CPU 核数",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(cpu_cores) as uptime from log.dnodes_info where dnode_ep = '$fqdn' interval ($interval)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Number",
     "type": "stat",
     "description": "VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(vnodes_num) as vnodes_num from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Masters",
     "type": "stat",
     "description": "Master VNodes 数量",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select last(masters) as masters from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current CPU Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 CPU 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "mem_taosd",
       "formatType": "Table",
       "sql": "select last(cpu_engine) from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Current Memory Usage of taosd",
     "type": "gauge",
     "description": "当前 taosd 线程 内存 使用率",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "memory",
       "formatType": "Time series",
       "sql": "select last(mem_engine) as taosd, last(mem_total) as total from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(disk_used) as used, last(disk_total) as total, last(disk_used) / last(disk_total) as percent from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU 资源占用情况。",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percent", "label": "使用占比" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(cpu_engine) as taosd, avg(cpu_system) as system from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "graph",
     "description": "内存资源占用情况",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "decmbytes", "label": "使用占比" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(mem_engine) as taosd, avg(mem_system) as system, avg(mem_total) as total from log.dnodes_info where dnode_ep='$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(datadir_l0_used) as level0_used, avg(datadir_l0_total) as level0_total, avg(datadir_l1_used) as level1_used, avg(datadir_l1_total) as level1_total, avg(datadir_l2_used) as level2_used, avg(datadir_l2_total) as level2_total from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(datadir_l0_used)/avg(datadir_l0_total) as level0_percent, avg(datadir_l1_used)/avg(datadir_l1_total) as level1_percent , avg(datadir_l2_used)/avg(datadir_l2_total) as level2_percent from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk Used Increasing Rate per Minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "alias": "level0",
       "formatType": "Time series",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l0_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level1",
       "formatType": "Time series",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l1_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      },
      {
       "alias": "level2",
       "formatType": "Time series",
       "sql": "select derivative(value, 1m, 0) from (select avg(datadir_l2_used) * 1024 as value from log.disks_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null))",
       "target": "select metric",
       "timeshift": {
        "period": null
       },
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "MBs", "label": "IO Rate" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(io_read_disk) as io_read_taosd, avg(io_write_disk) as io_write_taosd from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Net",
     "type": "graph",
     "description": "io",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "yaxes": [
      { "format": "Mbits", "label": "IO Rate" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(net_in) as net_in, avg(net_out) as net_out from log.dnodes_info where dnode_ep = '$fqdn' and ts >= $from and ts <= $to interval($interval) fill(null)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Login History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login Counts per Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "alias": "logins",
       "formatType": "Time series",
       "sql": "select count(*) from log.logs where ts >= $from and ts <= $to interval (1m)",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "TaosAdapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_request",
     "type": "timeseries",
     "description": "http请求统计",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(count) as request_total from log.taosadapter_restful_http_total where ts >= $from and ts <= $to interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(count) as request_fail from log.taosadapter_restful_http_fail where  ts >= $from and ts <= $to interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(count) as request_in_flight from log.taosadapter_restful_http_request_in_flight where ts >= $from and ts <= $to interval($interval)"
      }
     ]
    },
    {
     "title": "top 3 request endpoint",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select * from (select avg(count) as count from log.taosadapter_restful_http_total where  ts >= $from and ts <= $to group by endpoint) order by count desc limit 3",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(mem_percent) as mem_percent from log.taosadapter_system where ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "latency_quantile(ms)",
     "type": "graph",
     "description": "延迟分位数",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "formatType": "Time series",
       "sql": "select avg(quantile_1) as quantile_1 from log.taosadapter_restful_http_request_latency where ts >= $from and ts <= $to and request_uri != '/rest/ws' interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(quantile_2) as quantile_2 from log.taosadapter_restful_http_request_latency where ts >= $from and ts <= $to and request_uri != '/rest/ws' interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(quantile_5) as quantile_5 from log.taosadapter_restful_http_request_latency where ts >= $from and ts <= $to and request_uri != '/rest/ws' interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(quantile_9) as quantile_9 from log.taosadapter_restful_http_request_latency where ts >= $from and ts <= $to and request_uri != '/rest/ws' interval($interval)"
      },
      {
       "formatType": "Time series",
       "sql": "select avg(quantile_99) as quantile_99 from log.taosadapter_restful_http_request_latency where ts >= $from and ts <= $to and request_uri != '/rest/ws' interval($interval)"
      }
     ]
    },
    {
     "title": "top 3 failed request endpoint",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 5 },
     "targets": [
      {
       "formatType": "Table",
       "sql": "select * from (select avg(count) as count from log.taosadapter_restful_http_fail where ts >= $from and ts <= $to group by endpoint) order by count desc limit 3",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Used",
     "type": "gauge",
     "description": "CPU 使用率",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "disk_used",
       "formatType": "Time series",
       "sql": "select last(cpu_percent) as cpu_percent from log.taosadapter_system where ts >= $from and ts <= $to",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  }
 ]
}